# Generated by Django 4.1.7 on 2023-03-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='modeificado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='modeificado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='modeificado',
            new_name='modificado',
        ),
    ]
